language: node_js
node_js:
  - 7
  - 8
  - 9

cache: 
  yarn: true
  directories:
    - node_modules

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

after_success: npm run cover
