name: '@wizbii/angular-pipes'

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: 14
      - name: Install Dependencies
        run: yarn
      - uses: actions/cache@v2
        id: cache-install
        with:
          path: ./*
          key: ${{ github.sha }}

  lint:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: 14
      - uses: actions/cache@v2
        id: restore-install
        with:
          path: ./*
          key: ${{ github.sha }}
      - name: Lint lib
        run: yarn lint

  test:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: 14
      - uses: actions/cache@v2
        id: restore-install
        with:
          path: ./*
          key: ${{ github.sha }}
      - name: Test lib
        run: yarn test

  build:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: 14
      - uses: actions/cache@v2
        id: restore-install
        with:
          path: ./*
          key: ${{ github.sha }}
      - name: Build lib
        run: yarn build
